### ISSUE TITLE
help function need fix for usearch

### ISSUE THREAD

**Issue by badiku** [samyeyo/QuickRT#7]
► help('string')
>>> attempt to call a nil value (method 'search')

► string.search=string.usearch

► help('string')

Help item  : string
Category   : Module

Description: Strings in Luart are considered as containers for UTF8 characters, where in standard Lua, strings are containers for bytes, as explained in the Compatibility section The string module in Luart provides generic functions for string manipulation, such as finding and extracting substrings, and pattern matching.That means that all standard Lua strings functions can be used with UTF8 encoded strings using the standard Lua string functions : see the Lua 5.4 String module reference.The string module in Luart adds or modifies the following elements :

Contains: capitalize() search() lower() upper() similarity()

**Comment by samyeyo** [comment]
You are absolutely right, thank you 👍

**Comment by samyeyo** [comment]
It's now fixed
